package kanban

import com.raquo.laminar.api.L.{*, given}
import kanban.Pages.*
import kanban.models.*
import kanban.service.UserService.{getAllUsers, createUser}
import scala.util.{Failure, Success}
import scala.concurrent.ExecutionContext.Implicits.global

object AccountOverview {
  def apply(): HtmlElement = {
    // Variable to hold list of users
    val usersListVar: Var[List[User]] = Var(List())
    // Fetch all users asynchronously and update the variable
    getAllUsers().onComplete {
        case Success(users) =>
            usersListVar.set(users.toList)
        case Failure(exception) =>
            println(s"Failed to retrieve users from the db! Exception: $exception")
    }
    // Variable to hold the input data for the new user
    val newNameVar: Var[String] = Var("")
    val newAgeVar: Var[Int] = Var(0)
    val newEmailVar: Var[String] = Var("")

    // Function to add a new user
    def addNewUser(): Unit = {
      val newUser = User(
        id = None, // Assuming ID is auto-generated by the database
        name = newNameVar.now(),
        age = newAgeVar.now(),
        email = newEmailVar.now()
      )

      createUser(newUser).onComplete {
        case Success(_) =>
          println("User added successfully!")
          // Refresh the users list after adding the new user
          getAllUsers().onComplete {
            case Success(users) =>
              usersListVar.set(users.toList)
            case Failure(exception) =>
              println(s"Failed to retrieve users from the db! Exception: $exception")
          }
        case Failure(exception) =>
          println(s"Failed to add user. Exception: $exception")
      }
    }

    div(
      cls := "modal",
      div(
        cls := "modal-content",
        h2("Kontoübersicht"),

        // Displaying the list of users
        div(
          cls := "users-list",
          children <-- usersListVar.signal.map { users =>
            users.map { user =>
              div(
                cls := "user-item",
                child.text <-- Signal.fromValue(user.name),
                button(
                    cls := "delete-user-button",
                    "Löschen"
                )
              )
            }
          }
        ),

        // Form to add a new user
        div(
          cls := "add-user-form",
          input(
            cls := "user-name-input",
            placeholder := "Name",
            onInput.mapToValue --> newNameVar
          ),
          input(
            cls := "user-age-input",
            placeholder := "Alter",
            `type` := "number",
            onInput.mapToValue.filter(_.forall(_.isDigit)).map(_.toIntOption.getOrElse(0)) --> newAgeVar
          ),
          input(
            cls := "user-email-input",
            placeholder := "Email",
            onInput.mapToValue --> newEmailVar
          ),
          button(
            cls := "add-user-button",
            onClick --> { _ => addNewUser() },
            "Benutzer hinzufügen"
          )
        ),
        
        button(
          cls := "go-back-button",
          onClick --> { _ =>
            Router.pushState(KanbanBoardPage)
          },
          "Zurück"
        )
      )
    )
  }
}
